DROP TABLE WX;

CREATE TABLE WX ( 
	TIME		INT PRIMARY KEY	NOT NULL,
	TEMPERATURE	REAL,
	HUMIDITY	REAL,
	DEWPOINT	REAL,
	PRESSURE	REAL,
	WINDDIRMIN	REAL,
	WINDSPDMIN	REAL,
	WINDDIRAVE	REAL,
	WINDSPDAVE	REAL,
	WINDDIRMAX	REAL,
	WINDSPDMAX	REAL,
	RAINAMT24H	REAL,
	RAININTENSITY	REAL,
	RAINDURATION	REAL,
	HAILAMT24H	REAL,
	HAILINTENSITY	REAL,
	HAILDURATION	REAL);


